Sweet alert
GeorgiAsenov/vue-auth-training-app pull request #1
Opened 2019-04-15 09:39 UTC by GeorgiAsenov

Тук би трябвало да ги виждаш промените

2019-04-15 11:10 UTC, dobromir-hristov commented
Така, няколко неща.
Не си импортнал CSS-a.
Когато направиш сървис, ти можеш да го импортваш навсякъде и да го ползваш, било то във Vuex или в Router.
Направи си сървиса така, че да ти дава няколко хелпъра като например: `success`, `errror` които да са функции, които да подават параметри към SweetAlert, но да извикват този тип нотификации. 
После това можеш да го прикачиш към Vue,prototype за да го ползваш в компонентите си.

От компонентите, апито трябва да изглежда нещо подобно:
```
this.$notify.success({ message: 'someMessage' })
this.$notify.error({ message: 'WARNING' })
```

Питай Сашо ако имаш нужда, на него му го показах.

2019-04-16 10:14 UTC, dobromir-hristov requested changes
Изглежда добре като за начало. Ами ако искам да подам още параметри към success? като например времетраенето?
Как бихме могли да подадем всички параметри от обекта към `.fire` метода, оставяйки `type` :)

2019-04-16 10:15 UTC, GeorgiAsenov commented
Сега го рефактурирах. предполагам че вървя към добре?

2019-04-16 11:08 UTC, GeorgiAsenov commented
имаш предвид да се изреждат всички propertiy-та тук?
![image](https://user-images.githubusercontent.com/32931411/56204855-10ae8100-6051-11e9-8d4f-cd82e1788061.png)

2019-04-16 11:13 UTC, dobromir-hristov commented
Да. Искам да можеш да кажеш на `success` метода всякакви параметри и то да ги подаде към функцията на `swal`, без да трябва да ги изреждаш 1 по 1.

2019-04-16 11:38 UTC, GeorgiAsenov commented
предполагам, че това имаше предвид?

2019-04-16 12:35 UTC, dobromir-hristov commented
Е как така? Как ще подам какво съобщение искам?

2019-04-16 13:16 UTC, GeorgiAsenov commented
Така разбрах, ти каза без да се изреждат едно по едно, и същевременно да се подават. Тоест полседно да се подават?

2019-04-16 14:43 UTC, dobromir-hristov requested changes
Искам да мога да направя следното:
```
this.$notify.success({
message: 'Some text',
title: 'ERROR!',
position: 'top-start',
showConfirmButton: true
})
```
но и също така просто да мога и това:
```
this.$notify.error({
 message: 'Wrong name'
})
```

Демек, да мога да подавам каквито искам конфигурационни параметри, но да си има някакви дефолтни стойности.

2019-04-18 18:34 UTC, dobromir-hristov approved these changes

2019-04-18 18:34 UTC, dobromir-hristov commented
Айде мърджвай го това :)

2019-04-18 19:27 UTC, merged